# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 12:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=100)),
                ('short_description', models.TextField(help_text='max_length = 200', max_length=200)),
                ('address1', models.TextField(max_length=100)),
                ('address2', models.TextField(max_length=100)),
                ('tell', models.IntegerField()),
                ('instagram', models.URLField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('representative', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
                ('address1', models.CharField(help_text='Address Field 1', max_length=100)),
                ('address2', models.CharField(help_text='Address Field 2', max_length=100)),
                ('tell', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_source', models.ImageField(upload_to='')),
                ('short_description', models.TextField(max_length=100)),
                ('long_description', models.TextField(max_length=500)),
                ('date_created', models.DateField(verbose_name=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='UserExpanded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_source', models.FileField(upload_to='')),
                ('short_description', models.TextField(max_length=100)),
                ('long_description', models.TextField(max_length=500)),
                ('date_created', models.DateField(verbose_name=datetime.date)),
            ],
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='our_pictures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Pictures'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='our_videos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Videos'),
        ),
    ]
