# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='instagram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='short_description',
            field=models.TextField(help_text='Max length 200', max_length=200),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='date_created',
            field=models.DateField(),
        ),
    ]
