# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170508_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='our_pictures',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='our_videos',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='userexpanded',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
        migrations.DeleteModel(
            name='UserExpanded',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
