# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 06:15
from __future__ import unicode_literals

import blog.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20170508_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to=blog.models.user_directory_path)),
                ('short_description', models.TextField(help_text='Max length 200', max_length=200)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('instagram', models.EmailField(max_length=254)),
                ('info_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, help_text='Customer Id unique in whole application', primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('representative', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
                ('address1', models.CharField(help_text='Address Field 1', max_length=100)),
                ('address2', models.CharField(help_text='Address Field 2', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_source', models.ImageField(upload_to=blog.models.user_directory_path)),
                ('project_name', models.CharField(max_length=20)),
                ('short_description', models.TextField(max_length=100)),
                ('long_description', models.TextField(max_length=500)),
                ('date_created', models.DateField()),
                ('date_added', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('birth_date', models.DateField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('video_path', models.FileField(upload_to=blog.models.user_directory_path)),
                ('short_description', models.TextField(max_length=100)),
                ('long_description', models.TextField(max_length=500)),
                ('date_created', models.DateField()),
                ('date_added', models.DateField(verbose_name=datetime.date(2017, 5, 9))),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='pictures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Pictures'),
        ),
        migrations.AddField(
            model_name='customer',
            name='videos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Videos'),
        ),
    ]
