# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170509_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='instagram',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.UserProfile'),
        ),
    ]
