# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_profile_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Picture',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name_plural': 'Companies information'},
        ),
    ]
