# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170509_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic_source',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FilePathField(),
        ),
    ]
