# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170509_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name_plural': 'Company information'},
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_photo',
            field=models.ImageField(blank=True, upload_to='uploaded/profile/picture'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, help_text='Address Field 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic_source',
            field=models.ImageField(upload_to='uploaded/customer/pics'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FileField(upload_to='uploaded/customer/videos'),
        ),
    ]
